---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: $SERVICE   
  template:
    metadata:
      labels:
        app: $SERVICE 
    spec:
      imagePullSecrets:
      - name: $SECRET_NAME     
      containers:
      - name: java-$SERVICE 
        image: $IMAGE_NAME  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12


---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE-svc
spec:
#  type: NodePort  
  type: ClusterIP
  selector:
    app: $SERVICE 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $SERVICE-ingress 
spec:
  rules:
  - host: $SERVICE.sx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: $SERVICE-svc
          servicePort: 80
